### ISSUE TITLE
Possible to change label to RGB?

### ISSUE THREAD

**Issue by Night1099** [ader47/jittor-jieke-semantic_images_synthesis#1]
Is this modifiable to do RGB 2 RGB synthesis like in pix2pix?

**Comment by ader47** [comment]
> Is this modifiable to do RGB 2 RGB synthesis like in pix2pix?

yes，you can refer to ‘Semantic Image Synthesis via Diffusion Models’ in pixel space, the img2img method is applicable in pixel space too, but training diffusion model in pixel space will take a huge amount of resources.

**Comment by ader47** [comment]
> Is this modifiable to do RGB 2 RGB synthesis like in pix2pix?

Sorry,I misunderstood what you meant, it is possible to change label to RGB.  It can synthesize images that follow the label, such as Canny, sketch. But I have not tested the indicators.

**Comment by ader47** [comment]
> > Is this modifiable to do RGB 2 RGB synthesis like in pix2pix?
> 
> Sorry,I misunderstood what you meant, it is possible to change label to RGB. It can synthesize images that follow the label, such as Canny, sketch. But I have not tested the indicators.

Just replace the first label Conv layer to 3 input channels Conv layer.

**Comment by Night1099** [comment]
Could I pay you for the service of making a fork for this with a correct data loader? @ader47 50$?

I tried to implement but failed
